spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/
    username: postgres
    password: postgres
    database: postgres[.idea](.idea)
    driverClassname: org.postgresql.Driver